---
# maintains versions and can overwrite all.yml
avail:
  validator:
    version: v2.2.5.0
    grandpa_authority_id: "0x9454703654730ee4b61c9c546810bc786c915227b6bdec3c4de132bf76e1e728"
    node:
      version: v18.20.5
  fullnode:
    version: v2.2.5.0
