$ANSIBLE_VAULT;1.1;AES256
65383531633433623563346538326562316530366365623061383935306431323735373561636265
6137623766303465613830373666343639663561353633360a393231623635366134373465303230
34363234653462323262303834663631363534373231333436303436623964386139313264323162
6134306136336461320a386136613362373563343535386235613238643331616366653463613036
32623866343835363562353232613966303461343339613462393861633064613362313334393365
66323332653762363161653930646561373437336631633639343261323263306338663434356338
65313931633932303961643830396439323735373438623462326535616635613638646665336336
30393433623331323038313835326235626535636336313165663232373238386633613132356666
61623862613238653332336262613364373838376662633736323039336362323032326261326166
64306435653539663933376338383837653139616366666235366439396530636463373739616631
38333334386261636232366231653535646331373066623933666133363565616537316130333138
37663435303735386131613938353235353466313832653262653131313337336339323730303266
31656463393331396366383666656636333464663863633031633135633966656238666639303065
35363137323838663330336565636262366130626535343531626163666564663934333234636462
313962626364313533383962326633346339
