---
- name: Fetch the service binary
  ansible.builtin.get_url:
    url: "{{ vara[type].source_url }}/{{ vara[type].version }}/{{ node_default_binary_name[project] }}"
    dest: "{{ node_bin_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service
